package com.example.nempille

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.navigation.compose.rememberNavController
import com.example.nempille.ui.navigation.AppNavHost
import com.example.nempille.ui.theme.NemPilleTheme
import dagger.hilt.android.AndroidEntryPoint

//main entry point
@AndroidEntryPoint //tells 'u can inject dependencies in this Activity'
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            //material 3 generated by template
            NemPilleTheme {
                // NavController remembers the current navigation state (current screen).
                val navController = rememberNavController()
                // Surface gives a background using the current Material theme.
                Surface(
                    color = MaterialTheme.colorScheme.background
                ) {
                    //NavHost with all the destinations
                    AppNavHost(navController = navController)
                }
            }
        }
    }
}

@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    Text(
        text = "Hello $name!",
        modifier = modifier
    )
}

@Preview(showBackground = true)
@Composable
fun GreetingPreview() {
    NemPilleTheme {
        Greeting("Android")
    }
}