package com.example.nempille.data.local.entity

import androidx.room.Dao
import androidx.room.Entity
import androidx.room.PrimaryKey

//this annotation tells Room that this class
//represents table in the database

@Entity(tableName = "caregivers")
data class CaregiverEntity (
    //Primary key, autogenerated
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    //name of caregiver
    val name: String,

    //optional phone number to contact them
    val phoneNumber: String? = null,

    //relationship: daughter, nurse etc
    val relationToPatient: String? = null,
)