package com.example.nempille.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

//this annotation tells Room that this class
//represents table in the database
@Entity(tableName = "patients")

data class PatientEntity (
    @PrimaryKey(autoGenerate = true)
    //PK autogenerated id for each row
    val id: Int = 0,
    //name of the patient
    val name: String,
    //age - optional (null)
    val age: Int? = null,
    //optional notes (example: "he is with diabetes", "need help..."
    val notes: String? = null
)

//why entity? 1. room stores kotlin objects inside SQLite database
//each entity - one table
//each property - one column