package com.example.nempille.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

// This represents the "users" table in SQLite
@Entity(tableName = "users")
data class UserEntity(
    // Primary key, autogenerated
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    // Name of the user (patient or caregiver)
    val name: String,

    //age - optional (null)
    val age: Int? = null,

    // Optional phone number
    val phoneNumber: String? = null,

    // We store the role as String ("PATIENT" / "CAREGIVER")
    // and convert it to/from UserRole in the domain layer
    val role: String,

    //email
    val email: String,

    // bcrypt hash (includes salt + cost)
    val passwordHash: String
)